---

# Passwords are left unencrypted on purpose.
# I am well aware and accustomed with ansible-vault.

# Might be of interest
KIBANA_FQDN: "kibby.cloud.aoi.ee"
DOMAIN_NAME: "cloud.aoi.ee"

# DigitalOcean
DIGITALOCEAN_REGION: ams3
DIGITALOCEAN_IMAGE: ubuntu-22-04-x64
DIGITALOCEAN_PROJECT_NAME: PipeELK

# SSH key settings
SSH_NAME: ansible
SSH_PUBLIC_KEY: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
SSH_PRIVATE_KEY: "~/.ssh/id_rsa"

# ElasticSearch
CLUSTER_NAME: "PipeELK-cluster"
KIBANA_ELASTIC_USER: "kibana_system"
KIBANA_ELASTIC_PASSWORD: "elastic1234"
ELASTIC_PASSWORD: "elastic1234"
ELASTIC_CA_KEYSTORE_PASSWORD: "elastic1234"
ELASTIC_KEYSTORE_PASSWORD: "elastic1234"

# Kibana
NGINX_CERTIFICATE_PATH: "/etc/nginx/ssl/kibby.cloud.aoi.ee.crt"
NGINX_CERTIFICATE_KEY_PATH: "/etc/nginx/ssl/kibby.cloud.aoi.ee.key"
KIBANA_WEB_USER: "PipeKibana"
KIBANA_WEB_PASSWORD: "KibanaDrive"


# Logstash
LOGSTASH_ELASTIC_USER: "logstash_system"
LOGSTASH_ELASTIC_PASSWORD: "elastic1234"
LOGSTASH_LISTEN_PORT: 5044
LOGSTASH_PLUGINS:
  - logstash-input-beats
  - logstash-filter-multiline