---

- name: Initialize droplets
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - secret.yaml
  roles:
    - digitalocean

- name: Install and Configure elasticsearch
  hosts:
    - elastic01
    - elastic02
    - elastic03
  become: true
  gather_facts: true
  roles:
    - elastic