---

- name: Initialize droplets
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - secret.yaml
  roles:
    - digitalocean

- name: Droplet base configuration
  hosts: droplets
  become: true
  gather_facts: false
  roles:
    - common

- name: Install and Configure logstash
  hosts: logstash
  become: true
  gather_facts: true
  roles:
    - logstash

- name: Install and Configure filebeat
  hosts: droplets
  become: true
  gather_facts: true
  roles:
    - filebeat
