---

- name: Wait for a Filebeat index to appear
  ansible.builtin.uri:
    url: "http://{{ hostvars['elastic01'].private_address }}:9200/_cat/indices?format=json"
    method: GET
    status_code: 200
    validate_certs: no
  register: filebeat_index_response
  until: filebeat_index_response.json | selectattr('index', 'search', 'filebeat') | list | length > 0
  retries: 10
  delay: 10
  changed_when: false

- name: Check if data view already exists
  ansible.builtin.uri:
    url: "https://{{ KIBANA_FQDN }}/api/data_views"
    method: GET
    status_code: 
      - 200 
      - 404
    validate_certs: no
  register: filebeat_data_view_response
  changed_when: false
  when: filebeat_index_response.json | selectattr('index', 'search', 'filebeat') | list | length > 0

- name: debug
  debug:
    msg: "{{ filebeat_data_view_response.json }}"

- name: Create filebeat data view
  ansible.builtin.uri:
    url: "https://{{ KIBANA_FQDN }}/api/data_views/data_view"
    method: POST
    status_code: 200
    validate_certs: no
    headers:
      Content-Type: "application/json"
      kbn-xsrf: "ansible"
    body: "{{ lookup('file', 'filebeat-data-view.json') }}"
    body_format: json
  register: filebeat_data_view_response
  when: filebeat_data_view_response.json.data_view | selectattr('title', 'search', 'filebeat') | list | length == 0
