---

- name: Wait for a Logstash index to appear
  ansible.builtin.uri:
    url: "https://{{ hostvars['elastic01'].private_address }}:9200/_cat/indices?format=json"
    method: GET
    status_code: 200
    url_username: "elastic"
    url_password: "{{ ELASTIC_PASSWORD }}"
    validate_certs: false
    force_basic_auth: true
  register: logstash_index_response
  until: logstash_index_response.json | selectattr('index', 'search', 'logstash') | list | length > 0
  retries: 10
  delay: 10
  changed_when: false

- name: Check if data view already exists
  ansible.builtin.uri:
    url: "https://{{ KIBANA_FQDN }}/api/data_views"
    method: GET
    status_code: 
      - 200 
      - 404
    validate_certs: false
    url_username: "elastic"
    url_password: "{{ ELASTIC_PASSWORD }}"
    force_basic_auth: true
  register: logstash_data_view_response
  changed_when: false
  when: logstash_index_response.json | selectattr('index', 'search', 'logstash') | list | length > 0

- name: Create filebeat data view
  ansible.builtin.uri:
    url: "https://{{ KIBANA_FQDN }}/api/data_views/data_view"
    method: POST
    status_code: 200
    validate_certs: false
    headers:
      Content-Type: "application/json"
      kbn-xsrf: "ansible"
    body: "{{ lookup('file', 'filebeat-data-view.json') }}"
    body_format: json
    url_username: "elastic"
    url_password: "{{ ELASTIC_PASSWORD }}"
    force_basic_auth: true
  register: logstash_data_view_response
  when: logstash_data_view_response.json.data_view | selectattr('title', 'search', 'logstash') | list | length == 0
