---

- name: Install elasticsearch
  ansible.builtin.apt:
    update_cache: true
    name: elasticsearch
    state: present

- name: Create directories for elasticsearch
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: 0755
  loop:
    - /usr/share/elasticsearch/data
    - /usr/share/elasticsearch/logs

- name: Copy template
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: 0644
  notify: Restart elasticsearch

- name: Ensure elasticsearch service is enabled
  ansible.builtin.service:
    name: elasticsearch
    enabled: true

# - name: Reset elastic password
#   shell: /usr/share/elasticsearch/bin/elasticsearch-reset-password -i -u elastic
#   args:
#     stdin: "y\n{{ ELASTIC_PASSWORD }}\n{{ ELASTIC_PASSWORD }}"
#   changed_when: false
#   notify: Restart elasticsearch

# - name: Reset kibana password
#   shell: /usr/share/elasticsearch/bin/elasticsearch-reset-password -i -u "{{ KIBANA_ELASTIC_USER }}"
#   args:
#     stdin: "y\n{{ KIBANA_ELASTIC_PASSWORD }}\n{{ KIBANA_ELASTIC_PASSWORD }}"
#   changed_when: false
#   notify: Restart elasticsearch